# Generated by Django 4.0.1 on 2024-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
