# Generated by Django 4.0.1 on 2022-04-29 03:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters allowed')])),
                ('usd_price', models.CharField(max_length=25)),
                ('volume', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Coins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteCoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=25)),
                ('favourite', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters allowed')])),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
            ],
            options={
                'verbose_name_plural': 'Favourites',
                'ordering': ['-created_at'],
            },
        ),
    ]
