# Generated by Django 4.0.1 on 2023-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=60)),
                ('coin_price', models.CharField(max_length=64)),
                ('coin_volume', models.CharField(max_length=200)),
            ],
        ),
    ]
