# Generated by Django 4.0.1 on 2022-03-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coins_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
