# Generated by Django 4.0.1 on 2023-03-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coin_price',
            new_name='USD_PRICE',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_volume',
            new_name='volume',
        ),
    ]
