# Generated by Django 4.0.1 on 2022-04-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='favcoin',
            name='usd_price',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='favcoin',
            name='volume',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='favcoin',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
