# Generated by Django 4.0.1 on 2022-03-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='usd_price',
            new_name='price_usd',
        ),
        migrations.RemoveField(
            model_name='coins',
            name='user',
        ),
    ]
