# Generated by Django 4.0.1 on 2022-03-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_favoritecoins_coin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecoins',
            name='coin_name',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
