# Generated by Django 4.0.4 on 2022-04-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('USD_PRICE', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
            ],
        ),
    ]
