# Generated by Django 4.0.1 on 2022-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favcoin_usd_price_favcoin_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favcoin',
            name='usd_price',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='favcoin',
            name='volume',
            field=models.CharField(default='', max_length=30),
        ),
    ]
