# Generated by Django 4.0.1 on 2023-03-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='USD_PRICE',
            field=models.CharField(default='20.00', max_length=64),
        ),
    ]
