# Generated by Django 4.0.1 on 2022-03-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_usd_price_coins_price_usd_remove_coins_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='date_added',
        ),
    ]
