# Generated by Django 4.0.1 on 2022-03-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_favoritecoins_coin_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteCoins',
            new_name='FavoriteCoin',
        ),
    ]
