# Generated by Django 4.0.4 on 2022-04-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='USD_PRICE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
