# Generated by Django 4.0.1 on 2022-03-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_coins_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='date_added',
        ),
    ]
