# Generated by Django 4.0.4 on 2022-04-28 02:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_coin_usd_price_alter_coin_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_coins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None),
            preserve_default=False,
        ),
    ]
