# Generated by Django 4.0.1 on 2022-03-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_favoritecoins_favoritecoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
