# Generated by Django 4.0.4 on 2022-04-28 02:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_favourite_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_coins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None),
        ),
    ]
