# Generated by Django 4.0.1 on 2022-03-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritecoin',
            old_name='user',
            new_name='username',
        ),
    ]
