# Generated by Django 4.0.1 on 2022-03-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='favourite',
            name='name',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coins',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
