# Generated by Django 4.0.1 on 2022-03-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_favoritecoin_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritecoin',
            old_name='coin_name',
            new_name='favourite',
        ),
    ]
