# Generated by Django 4.0.1 on 2022-03-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_coin_name_favoritecoin_favourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteCoin',
            new_name='FavouriteCoin',
        ),
    ]
