# Generated by Django 4.0.1 on 2022-03-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_favourite_options_favourite_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='name',
        ),
    ]
