# Generated by Django 4.0.1 on 2022-03-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_favoritecoin_favouritecoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritecoin',
            old_name='favourite',
            new_name='favourite_coin',
        ),
        migrations.RenameField(
            model_name='favouritecoin',
            old_name='username',
            new_name='user',
        ),
    ]
