# Generated by Django 4.0.1 on 2022-03-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_favouritecoin_favourite_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritecoin',
            old_name='favourite_coin',
            new_name='coin_name',
        ),
        migrations.AlterUniqueTogether(
            name='favouritecoin',
            unique_together={('user', 'coin_name')},
        ),
    ]
