# Generated by Django 4.0.1 on 2022-03-13 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_favourite_coin_favouritecoin_coin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_coins', to=settings.AUTH_USER_MODEL),
        ),
    ]
